language: ruby
rvm:
  - 2.2

addons:
  postgresql: "9.4"

before_script:
  - psql -c 'create database lunchesorderingtest;' -U postgres

script:
  - RAILS_ENV=test bundle exec rake db:schema:load --trace
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec/

